# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4af4276a7b6eb86b0ae7b7c23c51c02a35dc372908b1e049fd316cdc48bb0239f4fc5e024b6f5d429e83f938cdea776c109c8c99e0f980c667b69cb53ea91d7b

test:
  secret_key_base: 1691ef0b42b78538defbb3fad4eac3829f916a8f6600f44da01ea86f5e7e05d4f254ef5d86c7a32c1469c68e353924416cf86dd688e1096f2a329e98f8a62e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
